### PR TITLE
Provide reset pin support for I2C

### LINKED ISSUE #7: not working with 128x64 product 938
A user can't get much working with this 128x64 OLED: https://www.adafruit.com/product/938.
See https://forums.adafruit.com/viewtopic.php?f=60&t=128946.

I happen to have one of these and have confirmed the problem. `.invert()` works, and so does `.poweron()` and `.poweroff()`, but nothing else really. Reconfirmed that library works fine with a 128x32 FeatherWing.

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #7. Tested on an Adafruit 938 128x64 display, both with I2C and SPI. Also tested with a FeatherWing OLED with I2C.

### CODE REVIEW

**Comment by ladyada** [comment]
looks good to me, do you want to fix up the pylint before merging?

**Comment by dhalbert** [comment]
Tnx! I'll update the Learn Guide as well.

**Comment by ladyada** [comment]
oops i started doing that too! ill wrap it up and you can check it

**Comment by dhalbert** [comment]
The SPI example is wrong: uses RPi pin designations, and the args need to be `DigitalInOut`s rather than just pin names.

**Comment by ladyada** [comment]
ok i did I2C example and will fix SPI now
https://learn.adafruit.com/micropython-hardware-ssd1306-oled-display/circuitpython
check it?

**Comment by dhalbert** [comment]
Guide fixes look excellent! Thanks!

**Pull request merged**
