### PR TITLE
Add 0.42" Screen Compatibility 

### PR DESCRIPTION
**Pull request by TinyCircuits**
0.42" 72x40 pixel screens like this one: https://www.icbanq.com/icdownload/data/ICBShop/Board/HP7240-01-TSWG16P042-A-VER1.0.pdf

### CODE REVIEW

**Comment by ladyada** [comment]
this seems to break existing OLEDs by changing mapping - please test against existing supported ones

**Comment by TinyCircuits** [comment]
Sorry! We minimized the changes from the original, changes should only apply to unsupported screens now.

**Comment by tannewt** [comment]
Thanks for this! Let me know if you need help adding CircuitPython board defs for TinyCircuits boards!

I'd suggest adding a new keyword argument called `colstart` ([this is the same name as the native display support](https://github.com/adafruit/circuitpython/blob/master/shared-bindings/displayio/Display.c#L86)) to the `__init__` method instead of assuming a shift of 28 with a given width. It's really just an artifact of how the display manufacturer hooked the IC up to the display circuitry.

**Comment by TinyCircuits** [comment]
Checking in to see if there is anything I can do to help the change get pulled in? Thanks!

**Comment by ladyada** [comment]
looks good to me @makermelissa please retro-test the PR with a 128x32 and 128x64? i2c is fine, either it inits/displays or not :)

**Review by makermelissa — APPROVED** [review]
Both displays tested good.

**Pull request merged**
