### PR TITLE
add bouncing ball example

### PR DESCRIPTION
**Pull request by raidancampbell**
hopefully this one doesn't throw as many linting issues

### CODE REVIEW

**Review by jerryneedell — COMMENTED** [review]
Nice example and animation! The animation section is nicely commented. One minor concern
 is that as presented in the example with radius=5,  the "circle" appears as a "square".   It would be nice to include more comments in the code about what the draw_circle function is actually doing to make it more clear why. I would suggest a larger value for the demo. radius=8 has some better shape to it.

**Comment by jerryneedell** [comment]
After thinking about this some more and doing some searches to educate myself I think it would be sufficient just to reference something like https://en.wikipedia.org/wiki/Midpoint_circle_algorithm.    At least for me, it was not immediately obvious what it was doing.  This example serves 2 nice purposes - 1) animation and 2) circle drawing and it would be nice to demystify the circle drawing example a bit.

**Comment by raidancampbell** [comment]
Changes implemented via 74ff27ab3ec2ce4917ec0160fe003f0b76be34bf

**Comment by tannewt** [comment]
Looks great! Thanks!

**Pull request merged**
